### ISSUE TITLE
[JEST] Using jest cause error but not when run expo app

### ISSUE THREAD

**Issue by MichelBahl** [matt-oakes/redux-devtools-expo-dev-plugin#13]
I added redux-devtools-expo-dev-plugin transformIgnorePatterns but does not work.

jest error:

```javascript
Details:

    /Users/michaelbahl/Documents/expo/redux-devtools-expo-dev-plugin/examples/example-redux-toolkit/node_modules/redux-devtools-expo-dev-plugin/build/index.js:2
    import { compose } from "redux";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { createSlice, combineSlices, configureStore } from "@reduxjs/toolkit";
    > 2 | import devToolsEnhancer from "redux-devtools-expo-dev-plugin";
        | ^
      3 |
      4 | export const counterSlice = createSlice({
      5 |   name: "counter",

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1505:14)
      at Object.require (src/store.ts:2:1)
      at Object.require (src/Counter.tsx:5:1)
      at Object.require (App.tsx:3:1)
      at Object.require (src/__test__/App.test.tsx:1:1)
```

How could I use redux-devtools-expo-dev-plugin with jest ?

**Comment by martinvysnovsky** [comment]
I have just mocked it. Anyway, you do not need it in tests.

Configure store with condition:

```
 export const store = configureStore({
  ...
  enhancers:
    process.env.NODE_ENV === "development"
      ? (getDefaultEnhancers) =>
          getDefaultEnhancers().concat(devToolsEnhancer())
      : undefined,
});
```

Mock `redux-devtools-expo-dev-plugin` in jest setup file:

```
jest.mock("redux-devtools-expo-dev-plugin", () => {});
```

**Comment by matt-oakes** [comment]
Thanks for your comment.

Yes, mocking the module or avoiding importing it at all in test environments is the correct way to do this. Exactly which is best for you will be down to your specific test setup and is outside the scope of this project.

Thanks again for posting your solution!
